#!/usr/bin/env python3

import subprocess
import shutil

def compile_code():
    # Define the command
    compile = [
        'emcc',
        '-O3',
        'factorial.cc',
        '-o',
        'factorial.wasm',
        '-s',
        'EXPORTED_FUNCTIONS=["_factorial"]',
        '--no-entry'
    ]

    # Run the command with error checking
    try:
        result = subprocess.run(compile, check=True, capture_output=True, text=True)
        print("Compilation successful!")
        print(result.stdout)
        return True
    except subprocess.CalledProcessError as e:
        print("Compilation failed!")
        print(e.stderr)
        return False

def copy_file_to_browser_env():
    try:
        shutil.copy('./factorial.wasm', 'on_browser_env/')
        print("File copied successfully!")
    except FileNotFoundError as e:
        print("File copy failed!")
        print(e)

def run_wasm():
    try:
        result = subprocess.run(['wasmtime', 'run', 'factorial.wasm', '--invoke', 'factorial', '10'], check=True, capture_output=True, text=True)
        print("WASM run successful!")
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print("WASM run failed!")
        print(e.stderr)

def wasm_to_txt():
    try:
        result = subprocess.run(['wasm-objdump', '-x', 'factorial.wasm'], check=True, capture_output=True, text=True)
        with open('dump.txt', 'w') as f:
            f.write(result.stdout)
        print("WASM to TXT conversion successful!")
    except subprocess.CalledProcessError as e:
        print("WASM to TXT conversion failed!")
        print(e.stderr)

def wasm_to_wat():
    try:
        result = subprocess.run(['wasm2wat', 'factorial.wasm', '-o', 'factorial.wat'], check=True, capture_output=True, text=True)
        print("WASM to WAT conversion successful!")
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print("WASM to WAT conversion failed!")
        print(e.stderr)

def main():
    if compile_code():
        copy_file_to_browser_env()
        run_wasm()
        wasm_to_txt()
        wasm_to_wat()

if __name__ == "__main__":
    main()
